=== PhaniKumarDV/APIN100A/src/IPQ4019.ILQ.4.0/common/tools/sectools/config/xsd/fuseblower.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.qualcomm.com/fuseblower"
	xmlns:tns="http://www.qualcomm.com/fuseblower">

	<element name="fuseblower">
		<complexType>
			<sequence>
				<element name="metadata" type="tns:complex_metadata" />
				<element name="module" type="tns:complex_module" maxOccurs="unbounded"
					minOccurs="0" />
			</sequence>
		</complexType>
	</element>

	<complexType name="complex_metadata">
		<all>
			<element name="chipset" type="string" />
			<element name="version" type="string" />
		</all>
	</complexType>

	<complexType name="complex_module">
		<sequence>
			<element name="base_address" type="string" />
			<element name="description" type="string" maxOccurs="1"
					minOccurs="0" />
			<element name="fuse_region" type="tns:complex_fuse_region"
				maxOccurs="unbounded" minOccurs="0" />
		</sequence>
		<attribute name="id" type="string" use="required" />
	</complexType>

	<complexType name="complex_fuse_region">
		<sequence>
			<element name="description" type="string" maxOccurs="1"
					minOccurs="0" />
			<element name="fuse" type="tns:complex_fuse" maxOccurs="unbounded"
				minOccurs="0" />
		</sequence>
		<attribute name="id" type="string" use="required" />
	</complexType>

	<complexType name="complex_fuse">
		<sequence>
			<element name="address" type="string" />
			<element name="operation" type="string" />
			<element name="field" type="tns:complex_field" maxOccurs="unbounded"
				minOccurs="0" />
		</sequence>
		<attribute name="n" type="int"/>
		<attribute name="ignore" type="boolean"/>
	</complexType>

	<complexType name="complex_field">
		<all>
			<element name="description" type="string" maxOccurs="1"
					minOccurs="0" />
			<element name="owner" type="string" maxOccurs="1"
					minOccurs="0" />
			<element name="value" type="string" />
			<element name="bits" type="string" />
		</all>
		<attribute name="id" type="string" use="required" />
	</complexType>

</schema>

=== PhaniKumarDV/APIN100A/src/IPQ4019.ILQ.4.0/common/tools/sectools/config/806x/806x_fuseblower_QC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
===============================================================================

  Copyright (c) 2013-2016 Qualcomm Technologies, Inc.
  All Rights Reserved.
  Confidential and Proprietary - Qualcomm Technologies, Inc.

===============================================================================
-->

<tns:fuseblower xmlns:tns="http://www.qualcomm.com/fuseblower"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.qualcomm.com/fuseblower ../xsd/fuseblower.xsd">

    <metadata>
        <chipset>806x</chipset>
        <version>1.0</version>
    </metadata>

    <module id="SECURITY_CONTROL_CORE">
        <base_address>0x00700000</base_address>
        <description></description>

        <fuse_region id="QFPROM_RAW_OEM_SEC_BOOT">
            <description></description>
            <fuse ignore="false" n="0">
                <address>0x00700310</address>
                <operation>BLOW</operation>
                <field id="SEC_BOOT1">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>7:0</bits>
                </field>
                <field id="SEC_BOOT2">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>15:8</bits>
                </field>
                <field id="SEC_BOOT3">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>23:16</bits>
                </field>
                <field id="SEC_BOOT4">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>31:24</bits>
                </field>
                <field id="SEC_BOOT5">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>39:32</bits>
                </field>
                <field id="SEC_BOOT6">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>47:40</bits>
                </field>
                <field id="SEC_BOOT7">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>55:48</bits>
                </field>
                <field id="FEC_VALUE">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>62:56</bits>
                </field>
            </fuse>
            <fuse ignore="false" n="1">
                <address>0x00700318</address>
                <operation>BLOW</operation>
                <field id="SEC_BOOT1">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>7:0</bits>
                </field>
                <field id="SEC_BOOT2">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>15:8</bits>
                </field>
                <field id="SEC_BOOT3">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>23:16</bits>
                </field>
                <field id="SEC_BOOT4">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>31:24</bits>
                </field>
                <field id="SEC_BOOT5">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>39:32</bits>
                </field>
                <field id="SEC_BOOT6">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>47:40</bits>
                </field>
                <field id="SEC_BOOT7">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>55:48</bits>
                </field>
                <field id="FEC_VALUE">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>62:56</bits>
                </field>
            </fuse>
            <fuse ignore="false" n="2">
                <address>0x00700320</address>
                <operation>BLOW</operation>
                <field id="SEC_BOOT1">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>7:0</bits>
                </field>
                <field id="SEC_BOOT2">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>15:8</bits>
                </field>
                <field id="SEC_BOOT3">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>23:16</bits>
                </field>
                <field id="SEC_BOOT4">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>31:24</bits>
                </field>
                <field id="SEC_BOOT5">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>39:32</bits>
                </field>
                <field id="SEC_BOOT6">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>47:40</bits>
                </field>
                <field id="SEC_BOOT7">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>55:48</bits>
                </field>
                <field id="FEC_VALUE">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>62:56</bits>
                </field>
            </fuse>
            <fuse ignore="false" n="3">
                <address>0x00700328</address>
                <operation>BLOW</operation>
                <field id="SEC_BOOT1">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>7:0</bits>
                </field>
                <field id="SEC_BOOT2">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>15:8</bits>
                </field>
                <field id="SEC_BOOT3">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>23:16</bits>
                </field>
                <field id="SEC_BOOT4">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>31:24</bits>
                </field>
                <field id="SEC_BOOT5">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>39:32</bits>
                </field>
                <field id="SEC_BOOT6">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>47:40</bits>
                </field>
                <field id="SEC_BOOT7">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>55:48</bits>
                </field>
                <field id="FEC_VALUE">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>62:56</bits>
                </field>
            </fuse>
        </fuse_region>

        <fuse_region id="QFPROM_RAW_SEC_KEY_DERIVATION_KEY">
            <description></description>
            <fuse ignore="false" n="0">
                <address>0x00700268</address>
                <operation>BLOW</operation>
                <field id="KEY_DATA0">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x000</value>
                    <bits>9:0</bits>
                </field>
                <field id="FEC_VALUE0">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>14:10</bits>
                </field>
                <field id="KEY_DATA1">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x000</value>
                    <bits>24:15</bits>
                </field>
                <field id="FEC_VALUE1">
                    <description></description>
                    <owner>QC</owner>
                    <value>0x00</value>
                    <bits>29:25</bits>
                </field>
                <field id="KEY_DATA2">
