=== PhaniKumarDV/APIN100A/src/IPQ8064.ILQ.4.0/common/tools/sectools/config/xsd/fuseblower_user.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.qualcomm.com/fuseblower"
	xmlns:tns="http://www.qualcomm.com/fuseblower">
	  

    <element name="fuseblower">
    	<complexType>
    		<sequence>
    			<element name="metadata" type="tns:metadata" maxOccurs="1" minOccurs="1"></element>
    			<element name="secdat" type="tns:secdat" maxOccurs="1" minOccurs="1"></element>
    			<element name="module" type="tns:module" maxOccurs="1" minOccurs="1"></element>
    		</sequence>
    	</complexType></element>
    
    <complexType name="metadata">
    	<sequence>
    		<element name="chipset" type="string"></element>
    		<element name="version" type="string"></element>
    	</sequence>
    </complexType>
    
    <complexType name="secdat">
    	<sequence>
    		<element name="file_info" type="string"></element>
    		<element name="file_version" type="int"></element>
    		<element name="fuse_version" type="int"></element>
    	</sequence>
    </complexType>
    
    <complexType name="module">
    	<sequence>
    		<element name="entry" type="tns:entry" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    </complexType>

    <complexType name="entry">
    	<sequence>
            <element name="description" type="string"></element>
            <element name="name" type="string"></element>
    		<element name="value" type="string"></element>
    	</sequence>

    	<attribute name="ignore" type="string"></attribute>
    </complexType>
</schema>

=== PhaniKumarDV/APIN100A/src/IPQ4019.ILQ.4.0/common/tools/sectools/config/806x/806x_fuseblower_USER.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
===============================================================================

  Copyright (c) 2013-2016 Qualcomm Technologies, Inc.
  All Rights Reserved.
  Confidential and Proprietary - Qualcomm Technologies, Inc.

===============================================================================
-->

<tns:fuseblower xmlns:tns="http://www.qualcomm.com/fuseblower"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.qualcomm.com/fuseblower ../xsd/fuseblower_user.xsd">

    <metadata>
        <chipset>806x</chipset>
        <version>1.0</version>
    </metadata>

    <secdat>
        <file_info>default dat file</file_info>
        <file_version>1</file_version>
        <fuse_version>1</fuse_version>
    </secdat>

    <module id="SECURITY_CONTROL_CORE">
        <entry ignore="false">
            <description>contains the OEM public key hash as set by OEM</description>
            <name>root_certhash</name>
            <value>0000000000000000000000000000000000000000000000000000000000000000</value>
        </entry>
        <entry ignore="true">
            <description>SHA256 signed root cert to generate root hash</description>
            <name>root_certfile</name>
            <value>./../../resources/testpki/qpsa_rootca.cer</value>
        </entry>
        <entry ignore="false">
            <description>PK Hash is in Fuse for SEC_BOOT1 : Apps</description>
            <name>SEC_BOOT1_PK_Hash_in_Fuse</name>
            <value>false</value>
        </entry>
        <entry ignore="false">
            <description>If PK Hash in Fuse is 0, then this index selects which of 16 keys in ROM to use</description>
            <name>SEC_BOOT1_rom_pk_hash_index</name>
            <value>0</value>
        </entry>
        <entry ignore="false">
            <description>Use Serial Num for secure boot authentication (0: Use OEM ID (Default), 1: Use Serial Num)</description>
            <name>SEC_BOOT1_use_serial_num</name>
            <value>false</value>
        </entry>
        <entry ignore="false">
            <description>PK Hash is in Fuse for SEC_BOOT2 : MBA</description>
            <name>SEC_BOOT2_PK_Hash_in_Fuse</name>
            <value>false</value>
        </entry>
        <entry ignore="false">
            <description>If PK Hash in Fuse is 0, then this index selects which of 16 keys in ROM to use</description>
            <name>SEC_BOOT2_rom_pk_hash_index</name>
            <value>0</value>
        </entry>
        <entry ignore="false">
            <description>Use Serial Num for secure boot authentication (0: Use OEM ID (Default), 1: Use Serial Num)</description>
            <name>SEC_BOOT2_use_serial_num</name>
            <value>false</value>
        </entry>
        <entry ignore="false">
            <description>PK Hash is in Fuse for SEC_BOOT3 : MPSS</description>
            <name>SEC_BOOT3_PK_Hash_in_Fuse</name>
            <value>false</value>
        </entry>
        <entry ignore="false">
            <description>If PK Hash in Fuse is 0, then this index selects which of 16 keys in ROM to use</description>
            <name>SEC_BOOT3_rom_pk_hash_index</name>
            <value>0</value>
        </entry>
        <entry ignore="false">
            <description>Use Serial Num for secure boot authentication (0: Use OEM ID (Default), 1: Use Serial Num)</description>
            <name>SEC_BOOT3_use_serial_num</name>
            <value>false</value>
        </entry>
        <entry ignore="false">
            <description>The OEM hardware ID</description>
            <name>oem_hwid</name>
            <value>0x0000</value>
        </entry>
        <entry ignore="false">
            <description>The OEM product ID</description>
            <name>oem_productid</name>
            <value>0x0000</value>
        </entry>
        <entry ignore="false">
            <description>prevents the Watch Dog from being disabled by the GPIO, true: ignore GPIO, false: use GPIO</description>
            <name>watchdog_enable</name>
            <value>false</value>
        </entry>
    </module>
</tns:fuseblower>
